export const GET_DISCOUNTS = "GET_DISCOUNTS";
export const GET_DISCOUNTS_SUCCESS = "GET_DISCOUNTS_SUCCESS";
export const GET_DISCOUNTS_FAIL = "GET_DISCOUNTS_FAIL";

export const CREATE_DISCOUNT = "CREATE_DISCOUNT";
export const CREATE_DISCOUNT_SUCCESS = "CREATE_DISCOUNT_SUCCESS";
export const CREATE_DISCOUNT_FAIL = "CREATE_DISCOUNT_FAIL";

export const UPDATE_DISCOUNT = "UPDATE_DISCOUNT";
export const UPDATE_DISCOUNT_SUCCESS = "UPDATE_DISCOUNT_SUCCESS";
export const UPDATE_DISCOUNT_FAIL = "UPDATE_DISCOUNT_FAIL";

export const DELETE_DISCOUNT = "DELETE_DISCOUNT";
export const DELETE_DISCOUNT_SUCCESS = "DELETE_DISCOUNT_SUCCESS";
export const DELETE_DISCOUNT_FAIL = "DELETE_DISCOUNT_FAIL"; 