export const GET_FLASH_SALES = "GET_FLASH_SALES";
export const GET_FLASH_SALES_SUCCESS = "GET_FLASH_SALES_SUCCESS";
export const GET_FLASH_SALES_FAIL = "GET_FLASH_SALES_FAIL";

export const CREATE_FLASH_SALE = "CREATE_FLASH_SALE";
export const CREATE_FLASH_SALE_SUCCESS = "CREATE_FLASH_SALE_SUCCESS";
export const CREATE_FLASH_SALE_FAIL = "CREATE_FLASH_SALE_FAIL";

export const UPDATE_FLASH_SALE = "UPDATE_FLASH_SALE";
export const UPDATE_FLASH_SALE_SUCCESS = "UPDATE_FLASH_SALE_SUCCESS";
export const UPDATE_FLASH_SALE_FAIL = "UPDATE_FLASH_SALE_FAIL";

export const DELETE_FLASH_SALE = "DELETE_FLASH_SALE";
export const DELETE_FLASH_SALE_SUCCESS = "DELETE_FLASH_SALE_SUCCESS";
export const DELETE_FLASH_SALE_FAIL = "DELETE_FLASH_SALE_FAIL"; 